SET search_path TO date;
-- Question 1 
SELECT *
FROM J; 
-- Question 2 
SELECT JNAME, CITY
FROM J
WHERE CITY = 'LONDON';
-- Question 3 
SELECT DISTINCT CITY
FROM J;
-- Question 5
SELECT *
FROM S
WHERE CITY = 'PARIS' AND STATUS = '10';
-- Question 6 
SELECT *
FROM S
WHERE CITY = 'LONDON' OR STATUS = '10'; 
-- Question 7
SELECT *
FROM SPJ
WHERE QTY >= 400 AND S = 'S5' AND P = 'P5';
-- Question 8
SELECT *
FROM S
WHERE CITY = 'Paris' AND STATUS <> '10';
-- Question 9
SELECT *
FROM SPJ
WHERE P = 'P2' AND QTY >=100 AND QTY <=300;
-- Question 10 
SELECT * 
FROM SPJ 
WHERE QTY IN ('100', '300', '500', '700', '900');
-- Question 12 
SELECT S.SNAME, P.PNAME, SPJ.QTY
FROM SPJ
JOIN S ON SPJ.S = S.S
JOIN P ON SPJ.P = P.P
ORDER BY S.SNAME, P.PNAME;
-- Question 13
SELECT S.SNAME, P.PNAME, J.JNAME, SPJ.QTY
FROM SPJ 
JOIN S ON SPJ.S = S.S
JOIN P ON SPJ.P = P.P
JOIN J ON SPJ.J = J.J
WHERE S.STATUS = 20 AND P.COLOUR = 'RED' AND P.CITY = 'PARIS';
-- Question 15
SELECT S.S, P.P, J.J, S.CITY, P.CITY, J.CITY
FROM S, P, J
WHERE S.CITY = P.CITY AND P.CITY = J.CITY;
-- Question 16
SELECT J.JNAME, P.COLOUR
FROM J CROSS JOIN P
ORDER BY J.JNAME, P.COLOUR;
--Question 17
SELECT *
FROM J
WHERE CITY IS NULL;